FROM harbor.k8s.temple.edu/library/httpd:2.4-alpine

WORKDIR /build

COPY . .

USER root

ENV PHPIZE_DEPS="autoconf dpkg-dev file g++ gcc libc-dev make pkgconfig re2c"

RUN apk add -U --no-cache \
      bash=5.1.4-r0 \
      libxslt=1.1.34-r1 \
      tzdata=2021e-r0 \
      shared-mime-info=2.1-r0 \
      imagemagick=7.0.11.13-r0 \
      mariadb-connector-c=3.1.13-r0 \
&&  apk add -U --no-cache --virtual build-dependencies \
      git=2.32.0-r0 \
      build-base=0.5-r2 \
      dpkg=1.20.9-r0 \
      libxslt-dev=1.1.34-r1 \
      mariadb-dev=10.5.13-r0 \
      mariadb-client=10.5.13-r0 \
      php7=7.4.25-r0 \
      php7-dev=7.4.25-r0 \
      php7-pear=7.4.25-r0 \
      php7-pear=7.4.25-r0 \
      wget=1.21.1-r1 \
      ghostscript=9.54.0-r1 \
      poppler-utils=21.06.1-r0 \
      libpng-dev=1.6.37-r1 \
      libjpeg-turbo-dev=2.1.0-r0 \
      freetype-dev=2.10.4-r1 \
      imagemagick-libs=7.0.11.13-r0 \
      imagemagick-dev=7.0.11.13-r0 \
      libxpm-dev \
      libwebp-dev \
      php7-mcrypt \
      php7-imagick 

ADD https://raw.githubusercontent.com/docker-library/php/master/docker-php-entrypoint /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-php-entrypoint

ADD https://raw.githubusercontent.com/docker-library/php/master/docker-php-ext-configure /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-php-ext-configure 

ADD https://raw.githubusercontent.com/docker-library/php/master/docker-php-ext-enable /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-php-ext-enable

ADD https://raw.githubusercontent.com/docker-library/php/master/docker-php-ext-install /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-php-ext-install

ADD https://raw.githubusercontent.com/docker-library/php/master/docker-php-source /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-php-source

ADD https://www.php.net/distributions/php-7.4.25.tar.xz /usr/src/php.tar.xz

RUN pecl channel-update pecl.php.net

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions 
RUN mkdir /conf.d
#RUN install-php-extensions gd xdebug
RUN install-php-extensions gd

RUN docker-php-ext-configure gd --with-jpeg=/usr/include/ --with-freetype=/usr/include/ 
RUN docker-php-ext-install -j"$(nproc)" iconv pdo pdo_mysql mysqli gd 
RUN yes | pecl install  mcrypt-1.0.3 || echo "pecl install encrypt: $?" 
RUN docker-php-ext-enable mcrypt || echo "docker-pop-ext-enable mcrypt: $?" 
RUN yes | pecl install imagick || echo "pecl install imagick $?" && docker-php-ext-enable imagick 
RUN wget --no-verbose "https://github.com/omeka/omeka-s/releases/download/v3.1.1/omeka-s-3.1.1.zip" -O /var/www/latest_omeka_s.zip \
&&  unzip -q /var/www/latest_omeka_s.zip -d /var/www/ \
&&  rm /var/www/latest_omeka_s.zip \
&&  rm -rf /var/www/html/ \
&&  mv /var/www/omeka-s/ /var/www/html/ \
&&  mkdir -p /var/www/html/config/ && mkdir -p /var/www/html/files/ && mkdir -p /var/www/html/modules/ && mkdir -p /var/www/html/themes/  \
&&  cp imagemagick-policy.xml /etc/ImageMagick-6/policy.xml \
&&  cp .htaccess /var/www/html/.htaccess \
&&  cp database.ini /var/www/html/config/ \
&&  cp local.config.php /var/www/html/config/ \
&&  chown -R www-data:www-data /var/www/html/ \
&&  chmod 600 /var/www/html/config/database.ini \
&&  chmod 600 /var/www/html/config/local.config.php \
&&  chmod 600 /var/www/html/.htaccess \
&&  echo "ServerName localhost" >> /etc/apache2/apache2.conf \
&&  wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip" && unzip awscliv2.zip && aws/install  \
&&  echo "ServerName localhost" >> /etc/apache2/apache2.conf 


WORKDIR /var/www/html

CMD ["sleep", "infinity"]
