<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'forgot-password');
$form->prepare();
?>
<h1><?php echo $translate('Forgot password'); ?></h1>
<?php

// Pass in the route/url you want to redirect to after the POST
$prg = $this->prg('/forgot-password', true);

if ($prg instanceof \Laminas\Http\PhpEnvironment\Response) {
    // Returned a response to redirect us.
    return $prg;
}

if ($prg === false) {
    // This wasn't a POST request, but there were no params in the flash
    // messenger; this is probably the first time the form was loaded.
    return ['form' => $myForm];
}

// $prg is an array containing the POST params from the previous request
$this->form->setData($prg);

echo $this->form()->openTag($form);
echo $this->formCollection($form, false);
?>
<button><?php echo $translate('Send password reset email'); ?></button>
<?php echo $this->form()->closeTag(); ?>
