<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'forgot-password');
$form->prepare();
?>
<h1><?php echo $translate('Forgot password'); ?></h1>
<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form, false);
#echo $configForm;
#echo $this->formElement($csrfForm->get($csrfForm->getName() . '_csrf'));
?>
<button><?php echo $translate('Send password reset email'); ?></button>
<?php echo $this->form()->closeTag(); ?>
