include:
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file:
      - "lint_docker.yaml"
      - "build_docker.yaml"
      - "security_scan.yaml"
      - "kubectl_commands.yaml"

variables:
  IMAGE: "tulibraries/tul_omeka-s"
  HARBOR: "harbor.k8s.temple.edu"
  HELM_EXPERIMENTAL_OCI: "1"

.export_variables: &export_variables
  - source .env
  - export VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"

before_script:
  - *export_variables

stages:
  - lint
  - build
  - scan
  - tag
  - deploy

lint:
  extends: .lint_docker
  variables:
    DF: ".docker/app/Dockerfile"
  except:
    - tags

build:
  stage: build
  extends: .build_image
  variables:
    DF: ".docker/app/Dockerfile --no-cache"
  except:
    - tags

scan:
  stage: scan
  extends: .scanimage_extended
  except:
    - tags

tag:
  stage: tag
  extends: .tag_image
  except:
    - tags

qa_deploy:
  variables:
    HARBOR_IMAGE: $HARBOR/tulibraries/tul_omeka-s
    RANCHER: rancher-np
    CLUSTER: dev-library1
  stage: deploy
  extends: .helm_setup
  only:
    - main
  script:
    - source .env
    - export TAG_VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"
    - helm pull oci://$HARBOR/tulibraries/exhibits-charts/exhibits --version "0.2.*" --untar
    - helm upgrade exhibits oci://$HARBOR/tulibraries/exhibits-charts/exhibits --version "0.1.*" --history-max=5 --namespace=exhibits-qa --values exhibits/values.yaml --set image.repository=$HARBOR_IMAGE:$TAG_VERSION

tag_release:
  stage: tag
  extends: .tag_image
  variables:
    TAG: $CI_COMMIT_TAG
  only:
    - tags

tag_prod:
  stage: tag
  extends: .tag_image
  variables:
    TAG: prod
  only:
    - tags

prod_deploy:
  variables:
    HARBOR_IMAGE: $HARBOR/tulibraries/tul_omeka-s
    RANCHER: rancher
    CLUSTER: prod-library1
  stage: deploy
  extends: .helm_setup
  only:
    - tags
  script:
    - helm pull oci://$HARBOR/tulibraries/exhibits-charts/exhibits --version "0.2.0" --untar
    - helm upgrade exhibits oci://$HARBOR/tulibraries/exhibits-charts/exhibits --version "0.2.0" --history-max=5 --namespace=exhibits-prod --values exhibits/values-prod.yaml --set image.repository=$HARBOR_IMAGE:$CI_COMMIT_TAG
