include:
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file:
      - "lint_docker.yaml"
      - "build_docker.yaml"
      - "security_scan.yaml"
      - "kubectl_commands.yaml"

variables:
  IMAGE: "tulibraries/tul_omeka-s"

.export_variables: &export_variables
  - source .env
  - export VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"

before_script:
  - *export_variables

stages:
  - lint
  - build
  - scan
  - tag
  - deploy

lint:
  extends: .lint_docker
  variables:
    DF: ".docker/app/Dockerfile"

build:
  stage: build
  extends: .build_image
  image: harbor.k8s.temple.edu/gitlab-ci/docker:20
  variables:
    DF: ".docker/app/Dockerfile --no-cache"
  services:
    - name: harbor.k8s.temple.edu/gitlab-ci/docker:20-dind
      command: ["--tls=false"]

scan:
  stage: scan
  extends: .scanimage_high
  allow_failure: false
  variables:
    THRESHOLD: 10

tag:
  stage: tag
  extends: .tag_image

qa_deploy:
  variables:
    IMAGE: harbor.k8s.temple.edu/tulibraries/tul_omeka-s
  stage: deploy
  extends: .helm_setup
  only:
    - main
  script:
    - *export_variables
    - helm repo add tulibraries https://$HARBOR/chartrepo/tulibraries
    - helm pull tulibraries/tul_omeka-s --untar
    - helm upgrade tul_omeka-s ./tul_omeka-s --history-max=5 --namespace=tul_omeka-s-qa --set image.repository=$IMAGE:$VERSION

prod_deploy:
  variables:
    IMAGE: harbor.k8s.temple.edu/tulibraries/tul_omeka-s
    CLUSTER: prod-library
    RANCHER: rancher
  stage: deploy
  extends: .helm_setup
  only:
    - tags
  script:
    - *export_variables
    - helm repo add tulibraries https://$HARBOR/chartrepo/tulibraries
    - helm pull tulibraries/tul_omeka-s --version 0.2.0 --untar
    - helm upgrade tul_omeka-s ./tul_omeka-s --values ./tul_omeka-s/values-prod.yaml --history-max 5 --namespace tul_omeka-s-prod --set image.repository=$IMAGE:$CI_COMMIT_TAG
