include:
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file:
      - "lint_docker.yaml"
      - "build_docker.yaml"
      - "security_scan.yaml"
      - "kubectl_commands.yaml"

variables:
  IMAGE: "tulibraries/tul_omeka-s"
  HARBOR: "harbor.k8s.temple.edu"
  HELM_EXPERIMENTAL_OCI: "1"

.export_variables: &export_variables
  - source .env
  - export VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"

before_script:
  - *export_variables

stages:
  - lint
  - build
  - scan
  - tag
  - deploy

lint:
  extends: .lint_docker
  variables:
    DF: ".docker/app/Dockerfile"

build:
  stage: build
  extends: .build_image
  image: $HARBOR/gitlab-ci/docker:20
  variables:
    DF: ".docker/app/Dockerfile --no-cache"
  services:
    - name: $HARBOR/gitlab-ci/docker:20-dind
      command: ["--tls=false"]

scan:
  stage: scan
  extends: .scanimage_high
  allow_failure: true
  variables:
    THRESHOLD: 10

tag:
  stage: tag
  extends: .tag_image

qa_deploy:
  variables:
    IMAGE: $HARBOR/tulibraries/tul_omeka-s
    RANCHER: rancher-np
    CLUSTER: dev-library
  stage: deploy
  extends: .helm_setup
  only:
    - main
  script:
    - *export_variables
    - helm pull oci://$HARBOR/tulibraries/exhibits-charts/exhibits --version "0.1.*" --untar
    - helm upgrade exhibits oci://$HARBOR/tulibraries/exhibits-charts/exhibits --version "0.1.*" --history-max=5 --namespace=exhibits-qa --values exhibits/values.yaml --set image.repository=$IMAGE:$VERSION

tag_prod:
  stage: tag
  extends: .tag_image
  variables:
    TAG: prod
  only:
    - tags

tag_release:
  stage: tag
  extends: .tag_image
  variables:
    TAG: $CI_COMMIT_TAG
  only:
    - tags

prod_deploy:
  variables:
    IMAGE: $HARBOR/tulibraries/tul_omeka-s
    RANCHER: rancher
    CLUSTER: prod-library0
  stage: deploy
  extends: .helm_setup
  only:
    - tags
  script:
    - helm pull oci://$HARBOR/tulibraries/exhibits-charts/exhibits --version "0.1.1" --untar
    - helm upgrade exhibits oci://$HARBOR/tulibraries/exhibits-charts/exhibits --version "0.1.1" --history-max=5 --namespace=exhibits-prod --values exhibits/values-prod.yaml --set image.repository=$IMAGE:$CI_COMMIT_TAG
